# Generated by Django 5.2.7 on 2025-11-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('idade', models.IntegerField()),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
    ]
